### ISSUE TITLE
Cost Estimation?

### ISSUE THREAD

**Issue by JiTao3** [zhouxh19/autoindex#1]
I want to figure out the cost estimation of the autoindex, the deep model used in the database. Can u give me some information about the model training and usage of the deep model in the database of the source code? @zhouxh19

**Comment by m729448362** [comment]
请问你找到Deep Regression for Cost Model的源码了吗？

**Comment by XuanheZhou** [comment]
Rather than directly using machine learning in the online cost model, we compute the CPU/IO costs based on the underlying database mechanisms, and learn the weights of CPU/IO costs with machine learning (u can check the cost model in autoindex paper or https://gitee.com/opengauss/openGauss-DBMind/tree/master/dbmind/components/index_advisor).
